language: go
sudo: required

go:
  - 1.6

services:
  - docker

cache:
  directories:
    - $HOME/gopath/src/github.com/sabakaio/kron/vendor
    - $HOME/gopath/vendor

install:
  - mkdir -p $GOPATH/bin
  - curl https://glide.sh/get | sh
  - glide install

script:
  - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo
  - docker build -t sabaka/kron .

after_success:
  - >
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push sabaka/kron;
    fi

