apiVersion: batch/v1
kind: Job
metadata:
  name: "test-job"
  labels:
    kron: "true"
  annotations:
    schedule: "@every 30s"
spec:
  completions: 0
  template:
    metadata:
      name: test-job
    spec:
      containers:
      - image: alpine:3.4
        name: test-job
        command: ["echo", "hello"]
      restartPolicy: Never
